### ISSUE TITLE
Topic Set: Date and Time

### ISSUE THREAD

**Issue by eunger9** [jhuckaby/simpleirc#1]
When joining a SimpleIRC channel, some IRC clients like to show you the date and time a topic was set.

Example from KiwiIRC: 
" Topic set by EB_Eric!~EB_Eric@4b389c41 at Invalid Date, NaN:NaN:NaN "

**Comment by jhuckaby** [comment]
Whew, that one was TOUGH.  It went extremely deep, into the bowels of the POE::Component::Server::IRC module.  Had to override a function and hack a fix, but it works.
